data:
  sample_rate: 8000                         # Частота дискретизации
  n_mels: 128                               # Количество Mel-фильтров
  n_fft: 400                                # Размер окна FFT
  hop_length: 180                           # Шаг между FFT окнами
  top_db: 80                                # Максимальная громкость в dB
  freq_mask: 15                             # FrequencyMasking спектрограмм
  time_mask: 20                             # TimeMasking спектрограмм
  blank_char: "_"                           # Символ CTC blank
  audio_dir: "morse_dataset/morse_dataset"  # Директория с аудиофайлами
  audio_save_dir: "morse_dataset/morse_dataset"   # Директория для сохраниниея загруженых аудиофайлов
  train_csv: "morse_dataset/train.csv"      # Путь к тренировочным данным
  test_csv: "morse_dataset/test.csv"        # Путь к тестовым данным
  val_size: 0.15                            # Размер валидационной выборки
  batch_size: 64
  seed: 42
  

model:
  num_classes: 45
  epochs: 70

  lr: 0.002
  weight_decay: 0.00001
  early_stopping_patience: 5
  lr_patience: 3
  lr_factor: 0.5

  first_fe_count: 16
  second_fe_count: 32
  third_fe_count: 32
  quad_fe_count: 32
  padding: "same"
  maxpool_kernel: 2
  kernel_size: 3
  neuron_count: 128
  gru_hidden: 256
  dropout: 0.3

  saved_models_dir: "src_data/saved_models"